ignoredBuiltDependencies:
  - yarn

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "@sentry/cli"
  - "@tailwindcss/oxide"
  - esbuild
  - msw
  - prisma
  - bcrypt

minimumReleaseAge: 2880
minimumReleaseAgeExclude:

packages:
  - "*"
