allowBuilds:
  "@prisma/engines": true
  esbuild: true
  msw: true
  prisma: true
  protobufjs: true
  sharp: true

allowedDeprecatedVersions:
  - glob@>=10.3.7 <10.5.0

ignoredBuiltDependencies:
  - yarn

minimumReleaseAge: 2880

minimumReleaseAgeExclude:
  - "coolify-ghcr-deploy"

onlyBuiltDependencies:
  - "@infisical/cli"
  - "@prisma/client"
  - "@prisma/engines"
  - "@tailwindcss/oxide"
  - core-js
  - esbuild
  - msw
  - prisma
  - protobufjs
  - sharp
