allowBuilds:
  "@prisma/engines": true
  esbuild: true
  msw: true
  prisma: true
  protobufjs: true
  sharp: true

allowedDeprecatedVersions:
  glob: ">=10.3.7 <10.5.0"

ignoredBuiltDependencies:
  - yarn

minimumReleaseAge: 2880

minimumReleaseAgeExclude:
  - "coolify-ghcr-deploy"
  - vite-plus
  - "@voidzero-dev/*"
  - oxlint
  - "@oxlint/*"
  - oxlint-tsgolint
  - "@oxlint-tsgolint/*"
  - oxfmt
  - "@oxfmt/*"
  - vitest
  - "@vitest/*"

onlyBuiltDependencies:
  - "@infisical/cli"
  - "@prisma/client"
  - "@prisma/engines"
  - "@tailwindcss/oxide"
  - core-js
  - esbuild
  - msw
  - prisma
  - protobufjs
  - sharp
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.7
  vite-plus: 0.2.7
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
