#!/usr/bin/env bash

set -eo pipefail

echo -e "\033[0;32m--- Generate types for route modules ---\033[0m"
react-router typegen

echo -e "\033[0;32m--- Run format, lint, and type checks ---\033[0m"
vp check --fix

echo -e "\033[0;32m--- Find unused dependencies, exports and files in your JavaScript and TypeScript projects ---\033[0m"
knip

echo -e "\033[0;32m--- Check for secrets ---\033[0m"
secretlint --format stylish
