import { diffLines } from "diff";
import { parseHTML } from "linkedom";

/**
 * Represents a node in the HTML tree.
 */
export type HTMLNode =
  | {
      type: "element";
      tag: string;
      attributes: Record<string, string>;
      children: HTMLNode[];
    }
  | {
      type: "text";
      content: string;
    };

/**
 * Parses an HTML string into a tree of elements and text nodes using DOM-compliant parsing.
 */
export function parseHTMLTree(html: string): HTMLNode[] {
  const { document } = parseHTML(html);
  for (const el of document.querySelectorAll("script")) el.remove();
  return domToTree(document.body ?? document.documentElement);
}

function domToTree(node: Element | Text): HTMLNode[] {
  const result: HTMLNode[] = [];
  for (const child of Array.from(node.childNodes)) {
    if (child.nodeType === child.TEXT_NODE) {
      const text = (child.textContent ?? "").replace(/\s+/g, " ").trim();
      if (text) result.push({ type: "text", content: text });
    } else if (child.nodeType === child.ELEMENT_NODE) {
      const el = child as Element;
      const attributes: Record<string, string> = {};
      for (const attr of Array.from(el.attributes)) {
        attributes[attr.name] = attr.value;
      }
      result.push({
        type: "element",
        tag: el.tagName.toLowerCase(),
        attributes,
        children: domToTree(el),
      });
    }
  }
  return result;
}

/**
 * Formats an HTMLNode[] tree into XML-style document with indentation.  The
 * HTML is formatted with 2-space indentation.  The HTML is escaped to prevent
 * XSS attacks.
 *
 * @param html - The HTML to format.
 * @returns The formatted HTML as a string.
 */
export function formatHTMLTree(html: HTMLNode[]): string {
  function formatNode(node: HTMLNode, indent = 0): string {
    const pad = "  ".repeat(indent);

    if (node.type === "text") {
      // Escape XML special chars
      const escaped = node.content
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;");
      return pad + escaped;
    } else {
      const attrs = node.attributes
        ? Object.entries(node.attributes)
            .sort(([a], [b]) => a.localeCompare(b))
            // Remove id attributes that are generated by the form library
            .filter(
              ([key, value]) =>
                !((key === "id" || key === "for") && value.match(/^_r_\d+_$/)),
            )
            .map(([key, value]) =>
              value === undefined || value === null || value === ""
                ? key
                : `${key}="${value.replace(/"/g, "&quot;")}"`,
            )
            .join(" ")
        : "";

      const tagStart =
        attrs && attrs.length > 0 ? `<${node.tag} ${attrs}>` : `<${node.tag}>`;
      const tagSelfClose =
        attrs && attrs.length > 0
          ? `<${node.tag} ${attrs} />`
          : `<${node.tag} />`;

      if (!node.children || node.children.length === 0) {
        // Use self-closing for void/self-closing tags
        if (
          /^(area|base|br|col|embed|hr|img|input|link|meta|source|track|wbr)$/i.test(
            node.tag,
          )
        ) {
          return pad + tagSelfClose;
        } else {
          return `${pad + tagStart}</${node.tag}>`;
        }
      }

      const children = node.children
        .map((child) => formatNode(child, indent + 1))
        .join("\n");
      return `${pad + tagStart}\n${children}\n${pad}</${node.tag}>`;
    }
  }

  return html.map((node) => formatNode(node, 0)).join("\n");
}

/**
 * Diffs two HTML trees and returns the diff as a string.  The diff is a string
 * with the lines that are added or removed.  The lines are prefixed with + or -
 * to indicate if they are added or removed.
 *
 * @param html - The HTML to diff. The HTML is assumed to be valid, well-formed
 * HTML (i.e., as returned by innerHTML). The HTML is sorted by attributes to
 * make the diffs easier to read.
 * @param original - The original HTML to diff against. The original HTML is
 * assumed to be valid, well-formed HTML (i.e., as returned by innerHTML). The
 * original HTML is sorted by attributes to make the diffs easier to read.
 * @returns The diff between the two HTML trees.
 */
export function diffHTMLs(html: string, original: string): string {
  const diffs = diffLines(html, original, { ignoreWhitespace: true });
  return diffs
    .map((diff) => (diff.added || diff.removed ? multipleLines(diff) : null))
    .filter(Boolean)
    .join("\n");
}

function multipleLines({
  added,
  count,
  value,
}: {
  added: boolean;
  count: number;
  value: string;
}) {
  return [
    added ? `added: ${count}` : `removed: ${count}`,
    ...value.split("\n").map((line) => (added ? `+ ${line}` : `- ${line}`)),
  ].join("\n");
}

/**
 * Recursively iterates the tree and removes the elements that match the given function.  The elements
 * are removed by reference, so the original tree is modified.
 *
 * @param html - The HTML tree to remove the elements from.
 * @param match - The function to match the elements to remove.
 * @example
 * removeElements(html, (node) => node.tag === "script"); // removes all <script> elements
 */
export function removeElements(
  html: HTMLNode[],
  match: (node: HTMLNode & { type: "element" }) => boolean,
): void {
  for (let i = html.length - 1; i >= 0; i--) {
    const node = html[i];
    if (node.type === "element" && match(node)) {
      html.splice(i, 1);
    } else if (node.type === "element" && node.children) {
      removeElements(node.children, match);
    }
  }
}

/**
 * Queries the HTML tree for elements with the given tag name. The elements are
 * returned with the type "element" to make it easier to use with the other
 * functions in this module.
 *
 * @param html - The HTML tree to query.
 * @param tagName - The tag name to query the HTML tree with.
 * @returns The elements with the given tag name.
 */
export function getElementsByTagName(
  html: HTMLNode[],
  tagName: string,
): (HTMLNode & { type: "element" })[] {
  const result: (HTMLNode & { type: "element" })[] = [];
  for (const node of html) {
    if (node.type === "element") {
      if (node.tag.toLowerCase() === tagName.toLowerCase())
        result.push({ ...node, type: "element" });
      result.push(...getElementsByTagName(node.children, tagName));
    }
  }
  return result;
}
