name: Deploy

on:
  - push
  - workflow_dispatch

jobs:
  test:
    name: Test
    runs-on: namespace-profile-rentail

    env:
      ANTHROPIC_API_KEY: "***REMOVED***"
      BETTER_AUTH_SECRET: "***REMOVED***"
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/postgres"
      DIRECT_URL: "postgresql://postgres:postgres@localhost:5432/postgres"
      DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
      REDIS_URL: "redis://localhost:6379"
      RESEND_API_KEY: "re_1234567890"

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - id: cache-node-modules
        uses: actions/cache/restore@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install NPM dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: pnpm install

      - uses: actions/cache/save@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Set PLAYWRIGHT_VERSION
        run: echo "PLAYWRIGHT_VERSION=$(pnpm exec playwright --version)" >> $GITHUB_ENV

      - id: cache-playwright
        uses: actions/cache/restore@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ env.PLAYWRIGHT_VERSION }}

      - name: Install Playwright (Chromium)
        if: steps.cache-playwright.outputs.cache-hit != 'true'
        run: pnpm exec playwright install chromium --with-deps

      - uses: actions/cache/save@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ env.PLAYWRIGHT_VERSION }}

      - name: Setup database schema (for testing)
        run: |
          pnpm prisma generate 
          pnpm prisma db push
        env:
          NODE_ENV: "test"

      - name: Check secrets
        run: pnpm secretlint "**/*" --format stylish

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Lint code
        run: biome lint

      - name: Generate React Router types
        run: pnpm react-router typegen

      - name: Check types
        run: pnpm tsc --noEmit --strict

      - name: Run Tests
        run: |
          rm -rf node_modules/.vite .react-router build
          pnpm vitest run --reporter verbose
        env:
          DEBUG: "browser,chat,server,test"

      - name: Upload Playwright Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-test-results
          path: __screenshots__

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v3

      - name: Deploy Prisma schema and seed database
        run: |
          doppler run --config prd -- pnpm prisma db push

      - name: Seed database
        run: |
          doppler run --config prd -- pnpm prisma db seed

      - name: Deploy to Vercel
        uses: nexterias/actions-vercel@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          org-id: "team_bjyg9pgn8TQQVP2NLMPnSYSN"
          prebuilt: false
          production: false
          project-id: "prj_SrqYHd1Olo0XfxQHLe9lyGfcoT9z"
          token: ${{ secrets.VERCEL_TOKEN }}
        env:
          SENTRY_AUTH_TOKEN: "***REMOVED***"
          SENTRY_ORG: "labnotes"
          SENTRY_PROJECT: "rentail"
