name: Scrape

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *" # 10 pm Pacific Time (PST/PDT) = 6 am UTC on the following day

jobs:
  scrape:
    name: Scrape
    runs-on: ubuntu-latest

    permissions:
      contents: read
      repository-projects: write

    env:
      DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - id: cache-node-modules
        uses: actions/cache/restore@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install NPM dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: pnpm install

      - uses: actions/cache/save@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Scrape Los Cerritos
        run: pnpm tsx scripts/scrapeLosCerritos.ts

      - name: Scrape Santa Monica
        run: pnpm tsx scripts/scrapeSantaMonica.ts

      - name: Scrape Stonewood
        run: pnpm tsx scripts/scrapeStonewood.ts

      - name: Seed database
        run: doppler run --config prd -- pnpm prisma db seed

      - name: Commit files
        run: |
          git config --local user.email "assaf@labnotes.org"
          git config --local user.name "GitHub Actions"
          git add prisma/seed/*.json
          git commit -m "Scrape properties" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "main"
