name: Scrape

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *" # 10 pm Pacific Time (PST/PDT) = 6 am UTC on the following day

jobs:
  scrape:
    name: Scrape
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      actions: write
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install NPM dependencies
        run: pnpm install

      - name: Install Playwright (Chromium)
        run: pnpm exec playwright install chromium --with-deps

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v3

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Scrape centers
        run: scripts/scrape-spaces.sh

      - name: Update database
        run: |
          doppler run --config prd -- pnpm prisma generate
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}

      - name: Format seed files
        run: biome format prisma/seed/*.json --fix

      - name: Commit files
        run: |
          git config --local user.email "assaf@labnotes.org"
          git config --local user.name "GitHub Actions"
          git add prisma/seed/*.json
          git commit -m "Scrape centers" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "main"
